// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb1R1OmpjP-nt4K7EpEHRKEy2LcF-smgo',
    appId: '1:897046943368:web:9cf592a92beeeb78a6713d',
    messagingSenderId: '897046943368',
    projectId: 'sambandha-d9081',
    authDomain: 'sambandha-d9081.firebaseapp.com',
    storageBucket: 'sambandha-d9081.firebasestorage.app',
    measurementId: 'G-ZYC0QXEPED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJYkpVaiqWT8AFyvuE9u2sLTZB73Jj5cQ',
    appId: '1:897046943368:android:d854f67e8a345713a6713d',
    messagingSenderId: '897046943368',
    projectId: 'sambandha-d9081',
    storageBucket: 'sambandha-d9081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_7QnOLNt3_dNc9ce2W56a4uUjNqPDAJc',
    appId: '1:897046943368:ios:672af2f7f5dd01fca6713d',
    messagingSenderId: '897046943368',
    projectId: 'sambandha-d9081',
    storageBucket: 'sambandha-d9081.firebasestorage.app',
    iosBundleId: 'com.example.sambandha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_7QnOLNt3_dNc9ce2W56a4uUjNqPDAJc',
    appId: '1:897046943368:ios:672af2f7f5dd01fca6713d',
    messagingSenderId: '897046943368',
    projectId: 'sambandha-d9081',
    storageBucket: 'sambandha-d9081.firebasestorage.app',
    iosBundleId: 'com.example.sambandha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb1R1OmpjP-nt4K7EpEHRKEy2LcF-smgo',
    appId: '1:897046943368:web:f951f0b77ec62c22a6713d',
    messagingSenderId: '897046943368',
    projectId: 'sambandha-d9081',
    authDomain: 'sambandha-d9081.firebaseapp.com',
    storageBucket: 'sambandha-d9081.firebasestorage.app',
    measurementId: 'G-P419XT60F0',
  );
}
